!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 32
  - - clip_range
    - 0.1
  - - ent_coef
    - 1.9e-06
  - - gae_lambda
    - 0.99
  - - gamma
    - 0.95
  - - learning_rate
    - 0.000208815
  - - max_grad_norm
    - 0.8
  - - n_epochs
    - 10
  - - n_steps
    - 64
  - - n_timesteps
    - 100000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(activation_fn=nn.ReLU, log_std_init=-0.338380542, ortho_init=False, net_arch=[dict(pi=[8,
      8], vf=[8, 8])])
  - - sde_sample_freq
    - 128
  - - vf_coef
    - 0.550970466
